services:
  main:
    image: ghcr.io/monashsmartcitylivinglab/idle-device-management:main
    build:
      context: .
    ports:
      - 4100:4100
    restart: unless-stopped
    volumes:
      - ./config.example.json:/opt/idle-device-management/config.json:ro