server:
  port: 4100
spring:
  application:
    name: idle-device-management
logging:
  config: classpath:logback.xml
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
idle-device-management:
  sites-config: ${SITES_CONFIG:#{"config.json"}}
  frontend-url: ${FRONTEND_URL:#{"http://localhost:3000"}}
  allow-all-cors-origins: ${ALLOW_ALL_CORS_ORIGINS:#{false}}