server:
  port: 4100
spring:
  application:
    name: idle-device-management
logging:
  config: classpath:logback-prod.xml
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
idle-device-management:
  sites-config: ${SITES_CONFIG:#{"config.json"}}